name: fordev
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.3
  equatable: ^2.0.5
  get: ^4.6.5
  flutter_secure_storage: ^6.0.0
  localstorage: ^4.0.0+1
  intl: ^0.17.0
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0

  #test -> para gerar teste no DART sem precisar do FLUTTER
  test: ^1.21.4

  #mockito -> Gerar versoes mocadas para gerar dubles de test em qualquer classe que tenhamos e classes de framework externos
  mockito: 5.3.2

  #faker -> gerar valores aleatórios (email fake, nome fake, numero fake, string fake... qualquer)
  faker: ^2.0.0

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700